version: '3'
services:
  server:
    build: 
      context: ./server
      args:
        port: '3001'
        dbConnectionString: 'mongodb://localhost:27017'
        dbName: 'todo'
    ports:
    - '3001:3001'
  db:
    image: mongo:4.1
    ports:
    - '27017:27017'