version: '3'
services:
  server:
    build: 
      context: ./server
      args:
        port: '3000'
        dbConnectionString: 'mongodb://database'
        dbName: 'todo'
    ports:
    - '3000:3000'
    links:
    - database
  database:
    image: mongo:4.1
    ports:
    - '27017:27017'